// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN9VEtiuj-Mun5i9sbHu9-SE_P4j_ncxk',
    appId: '1:973189622114:web:72ff7273c90746fd23a43b',
    messagingSenderId: '973189622114',
    projectId: 'musify-7fc28',
    authDomain: 'musify-7fc28.firebaseapp.com',
    storageBucket: 'musify-7fc28.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXwRmQG9h1-mpBS5WVnP7v86S4lMzksW0',
    appId: '1:973189622114:android:2675457e9c27e2e623a43b',
    messagingSenderId: '973189622114',
    projectId: 'musify-7fc28',
    storageBucket: 'musify-7fc28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5altqKrk_jrqHVF55XmeGxIXZOKee4io',
    appId: '1:973189622114:ios:e827e9f85dd4593d23a43b',
    messagingSenderId: '973189622114',
    projectId: 'musify-7fc28',
    storageBucket: 'musify-7fc28.appspot.com',
    iosBundleId: 'com.example.musify',
  );
}
